server.port=8085
spring.application.name=notification-service

spring.datasource.url=jdbc:postgresql://postgres:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

security.jwt.key.public=classpath:rsaKey.public