server.port=8086
spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://postgres:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true

security.jwt.key.public=classpath:rsaKey.public

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# match-service et payment-service
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.serialization.write-dates-as-timestamps=false

# Queues consommées (incoming)
rabbitmq.queues.booking-to-payment=booking.to.payment.queue
rabbitmq.queues.match-to-payment=match.payment.queue

# Queues publiées (outgoing)
rabbitmq.queues.payment-to-booking=payment.to.booking.queue

# Exchanges
rabbitmq.exchanges.payment-exchange=payment.exchange
rabbitmq.exchanges.booking-exchange=booking.exchange
rabbitmq.exchanges.match-exchange=match.exchange

# Routing keys (outgoing)
rabbitmq.routing-keys.payment-booking-status=payment.booking.status
rabbitmq.routing-keys.payment-match-status=payment.match.status